### ISSUE TITLE
Putting the apiKey in crashlytics.properties is useless

### ISSUE THREAD

**Issue by stoyicker** [plastiv/CrashlyticsDemo#2]
I keep getting the exception that the API key is missing from the manifest and that I should include it there.

**Comment by plastiv** [comment]
What version of the Fabric are you using? 
Are you sure that `crashlytics.properties` file is generated and contains both `apiKey` and `apiSecret`? 
Did you apply `apply plugin: 'io.fabric'` after aplying android plugin?
Did you enabled fabric plugin with `ext.enableCrashlytics = true`?

Manifest meta-tag is generated by the plugin, I'm sure about it. They might have changed that behaviour for some reason or most likely it's configuration issues.

**Comment by plastiv** [comment]
I have double checked, that I do not put meta tag at my manifest, but those lines are present at the `\build\intermediates\manifests\release\AndroidManifest.xml`. 
At the `\build\outputs\apk\manifest-merger-release-report.txt` I see next lines:

```
MERGED from com.crashlytics.sdk.android:crashlytics:2.2.1:7:5
MERGED from com.crashlytics.sdk.android:answers:1.1.1:7:5
MERGED from io.fabric.sdk.android:fabric:1.1.1:7:5
MERGED from io.fabric.sdk.android:fabric:1.1.1:7:5
MERGED from com.crashlytics.sdk.android:beta:1.1.1:7:5
MERGED from io.fabric.sdk.android:fabric:1.1.1:7:5
```

**Comment by stoyicker** [comment]
Alright that was an easy one to fix. I explicitely set ext.enableCrashlytics to false in my debug buildType as I understood that its purpose was to control the usage of Crashlytics, not where the data is fetched.
